//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/SampleInventoryInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/SampleInventoryInputAction.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @SampleInventoryInputAction: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @SampleInventoryInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""SampleInventoryInputAction"",
    ""maps"": [
        {
            ""name"": ""Inventory"",
            ""id"": ""77fbc33e-bf0f-4813-8697-56c7d3cd3c13"",
            ""actions"": [
                {
                    ""name"": ""BackpackSlot1"",
                    ""type"": ""Button"",
                    ""id"": ""52838137-ac1b-468c-ae64-6024de180895"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackpackSlot2"",
                    ""type"": ""Button"",
                    ""id"": ""e5890f49-f0fb-4ce2-90b8-b258c10b612a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackpackSlot3"",
                    ""type"": ""Button"",
                    ""id"": ""1ab14ad8-396c-4528-a2d2-3d07ea701655"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackpackSlot4"",
                    ""type"": ""Button"",
                    ""id"": ""739caab5-73aa-494d-90d8-c83291a32755"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackpackSlot5"",
                    ""type"": ""Button"",
                    ""id"": ""8584627e-1a22-452f-9773-b94b5f777059"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackpackSlot6"",
                    ""type"": ""Button"",
                    ""id"": ""a558d97f-fadf-4091-8e86-fa1ed2ad61b6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackpackSlot7"",
                    ""type"": ""Button"",
                    ""id"": ""28a91bdf-ca57-4cb9-b929-cb27422fb624"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackpackSlot8"",
                    ""type"": ""Button"",
                    ""id"": ""f10f740e-8714-4754-8388-e3e378299426"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackpackSlot9"",
                    ""type"": ""Button"",
                    ""id"": ""e5193b99-66fb-49d7-8b75-d2cd1e0a6fc0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackpackSlot10"",
                    ""type"": ""Button"",
                    ""id"": ""f97f8c98-641d-4637-b39e-007029ed7b80"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""fdc02483-e904-4d12-ac76-db9a76d2cd09"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch"",
                    ""type"": ""Button"",
                    ""id"": ""377a986f-937c-4030-a9ef-3dae0bae3873"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrevNext"",
                    ""type"": ""Value"",
                    ""id"": ""a0a33802-aff3-4e05-a117-3ff9328a7a43"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6258dd3b-eb2f-45b0-8829-bb8c74705f00"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackpackSlot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3f4d5bc-4976-49ed-8772-8dd07d505075"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackpackSlot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0483f289-ee4e-48c3-a7db-e8e806adb1e8"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackpackSlot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9dab7b10-559f-4f59-adc3-36c21695bae1"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackpackSlot4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb2ad35e-e0d0-45d5-9f11-5a02e0d47151"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackpackSlot5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""347b656b-4e66-4d84-9a4e-79d4843531c3"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackpackSlot6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1648db99-f44b-4bbe-937e-9bba3c0dd64b"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackpackSlot7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0290539-9d5b-47ca-bb75-9f5c207d6119"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackpackSlot8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33585581-ce98-4f26-9c26-e05756eca58a"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackpackSlot9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e00cbcd-ba0a-475e-a677-cdf811317dbe"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackpackSlot10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a383b2e8-3d8a-401b-8706-70368352e164"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03195090-be38-4b26-a582-07896cda87e9"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86d0d2a3-89a3-40ae-ac70-87678eaac9e0"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Inventory
        m_Inventory = asset.FindActionMap("Inventory", throwIfNotFound: true);
        m_Inventory_BackpackSlot1 = m_Inventory.FindAction("BackpackSlot1", throwIfNotFound: true);
        m_Inventory_BackpackSlot2 = m_Inventory.FindAction("BackpackSlot2", throwIfNotFound: true);
        m_Inventory_BackpackSlot3 = m_Inventory.FindAction("BackpackSlot3", throwIfNotFound: true);
        m_Inventory_BackpackSlot4 = m_Inventory.FindAction("BackpackSlot4", throwIfNotFound: true);
        m_Inventory_BackpackSlot5 = m_Inventory.FindAction("BackpackSlot5", throwIfNotFound: true);
        m_Inventory_BackpackSlot6 = m_Inventory.FindAction("BackpackSlot6", throwIfNotFound: true);
        m_Inventory_BackpackSlot7 = m_Inventory.FindAction("BackpackSlot7", throwIfNotFound: true);
        m_Inventory_BackpackSlot8 = m_Inventory.FindAction("BackpackSlot8", throwIfNotFound: true);
        m_Inventory_BackpackSlot9 = m_Inventory.FindAction("BackpackSlot9", throwIfNotFound: true);
        m_Inventory_BackpackSlot10 = m_Inventory.FindAction("BackpackSlot10", throwIfNotFound: true);
        m_Inventory_Rotate = m_Inventory.FindAction("Rotate", throwIfNotFound: true);
        m_Inventory_Switch = m_Inventory.FindAction("Switch", throwIfNotFound: true);
        m_Inventory_PrevNext = m_Inventory.FindAction("PrevNext", throwIfNotFound: true);
    }

    ~@SampleInventoryInputAction()
    {
        UnityEngine.Debug.Assert(!m_Inventory.enabled, "This will cause a leak and performance issues, SampleInventoryInputAction.Inventory.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Inventory
    private readonly InputActionMap m_Inventory;
    private List<IInventoryActions> m_InventoryActionsCallbackInterfaces = new List<IInventoryActions>();
    private readonly InputAction m_Inventory_BackpackSlot1;
    private readonly InputAction m_Inventory_BackpackSlot2;
    private readonly InputAction m_Inventory_BackpackSlot3;
    private readonly InputAction m_Inventory_BackpackSlot4;
    private readonly InputAction m_Inventory_BackpackSlot5;
    private readonly InputAction m_Inventory_BackpackSlot6;
    private readonly InputAction m_Inventory_BackpackSlot7;
    private readonly InputAction m_Inventory_BackpackSlot8;
    private readonly InputAction m_Inventory_BackpackSlot9;
    private readonly InputAction m_Inventory_BackpackSlot10;
    private readonly InputAction m_Inventory_Rotate;
    private readonly InputAction m_Inventory_Switch;
    private readonly InputAction m_Inventory_PrevNext;
    /// <summary>
    /// Provides access to input actions defined in input action map "Inventory".
    /// </summary>
    public struct InventoryActions
    {
        private @SampleInventoryInputAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public InventoryActions(@SampleInventoryInputAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Inventory/BackpackSlot1".
        /// </summary>
        public InputAction @BackpackSlot1 => m_Wrapper.m_Inventory_BackpackSlot1;
        /// <summary>
        /// Provides access to the underlying input action "Inventory/BackpackSlot2".
        /// </summary>
        public InputAction @BackpackSlot2 => m_Wrapper.m_Inventory_BackpackSlot2;
        /// <summary>
        /// Provides access to the underlying input action "Inventory/BackpackSlot3".
        /// </summary>
        public InputAction @BackpackSlot3 => m_Wrapper.m_Inventory_BackpackSlot3;
        /// <summary>
        /// Provides access to the underlying input action "Inventory/BackpackSlot4".
        /// </summary>
        public InputAction @BackpackSlot4 => m_Wrapper.m_Inventory_BackpackSlot4;
        /// <summary>
        /// Provides access to the underlying input action "Inventory/BackpackSlot5".
        /// </summary>
        public InputAction @BackpackSlot5 => m_Wrapper.m_Inventory_BackpackSlot5;
        /// <summary>
        /// Provides access to the underlying input action "Inventory/BackpackSlot6".
        /// </summary>
        public InputAction @BackpackSlot6 => m_Wrapper.m_Inventory_BackpackSlot6;
        /// <summary>
        /// Provides access to the underlying input action "Inventory/BackpackSlot7".
        /// </summary>
        public InputAction @BackpackSlot7 => m_Wrapper.m_Inventory_BackpackSlot7;
        /// <summary>
        /// Provides access to the underlying input action "Inventory/BackpackSlot8".
        /// </summary>
        public InputAction @BackpackSlot8 => m_Wrapper.m_Inventory_BackpackSlot8;
        /// <summary>
        /// Provides access to the underlying input action "Inventory/BackpackSlot9".
        /// </summary>
        public InputAction @BackpackSlot9 => m_Wrapper.m_Inventory_BackpackSlot9;
        /// <summary>
        /// Provides access to the underlying input action "Inventory/BackpackSlot10".
        /// </summary>
        public InputAction @BackpackSlot10 => m_Wrapper.m_Inventory_BackpackSlot10;
        /// <summary>
        /// Provides access to the underlying input action "Inventory/Rotate".
        /// </summary>
        public InputAction @Rotate => m_Wrapper.m_Inventory_Rotate;
        /// <summary>
        /// Provides access to the underlying input action "Inventory/Switch".
        /// </summary>
        public InputAction @Switch => m_Wrapper.m_Inventory_Switch;
        /// <summary>
        /// Provides access to the underlying input action "Inventory/PrevNext".
        /// </summary>
        public InputAction @PrevNext => m_Wrapper.m_Inventory_PrevNext;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Inventory; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="InventoryActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(InventoryActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="InventoryActions" />
        public void AddCallbacks(IInventoryActions instance)
        {
            if (instance == null || m_Wrapper.m_InventoryActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InventoryActionsCallbackInterfaces.Add(instance);
            @BackpackSlot1.started += instance.OnBackpackSlot1;
            @BackpackSlot1.performed += instance.OnBackpackSlot1;
            @BackpackSlot1.canceled += instance.OnBackpackSlot1;
            @BackpackSlot2.started += instance.OnBackpackSlot2;
            @BackpackSlot2.performed += instance.OnBackpackSlot2;
            @BackpackSlot2.canceled += instance.OnBackpackSlot2;
            @BackpackSlot3.started += instance.OnBackpackSlot3;
            @BackpackSlot3.performed += instance.OnBackpackSlot3;
            @BackpackSlot3.canceled += instance.OnBackpackSlot3;
            @BackpackSlot4.started += instance.OnBackpackSlot4;
            @BackpackSlot4.performed += instance.OnBackpackSlot4;
            @BackpackSlot4.canceled += instance.OnBackpackSlot4;
            @BackpackSlot5.started += instance.OnBackpackSlot5;
            @BackpackSlot5.performed += instance.OnBackpackSlot5;
            @BackpackSlot5.canceled += instance.OnBackpackSlot5;
            @BackpackSlot6.started += instance.OnBackpackSlot6;
            @BackpackSlot6.performed += instance.OnBackpackSlot6;
            @BackpackSlot6.canceled += instance.OnBackpackSlot6;
            @BackpackSlot7.started += instance.OnBackpackSlot7;
            @BackpackSlot7.performed += instance.OnBackpackSlot7;
            @BackpackSlot7.canceled += instance.OnBackpackSlot7;
            @BackpackSlot8.started += instance.OnBackpackSlot8;
            @BackpackSlot8.performed += instance.OnBackpackSlot8;
            @BackpackSlot8.canceled += instance.OnBackpackSlot8;
            @BackpackSlot9.started += instance.OnBackpackSlot9;
            @BackpackSlot9.performed += instance.OnBackpackSlot9;
            @BackpackSlot9.canceled += instance.OnBackpackSlot9;
            @BackpackSlot10.started += instance.OnBackpackSlot10;
            @BackpackSlot10.performed += instance.OnBackpackSlot10;
            @BackpackSlot10.canceled += instance.OnBackpackSlot10;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @Switch.started += instance.OnSwitch;
            @Switch.performed += instance.OnSwitch;
            @Switch.canceled += instance.OnSwitch;
            @PrevNext.started += instance.OnPrevNext;
            @PrevNext.performed += instance.OnPrevNext;
            @PrevNext.canceled += instance.OnPrevNext;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="InventoryActions" />
        private void UnregisterCallbacks(IInventoryActions instance)
        {
            @BackpackSlot1.started -= instance.OnBackpackSlot1;
            @BackpackSlot1.performed -= instance.OnBackpackSlot1;
            @BackpackSlot1.canceled -= instance.OnBackpackSlot1;
            @BackpackSlot2.started -= instance.OnBackpackSlot2;
            @BackpackSlot2.performed -= instance.OnBackpackSlot2;
            @BackpackSlot2.canceled -= instance.OnBackpackSlot2;
            @BackpackSlot3.started -= instance.OnBackpackSlot3;
            @BackpackSlot3.performed -= instance.OnBackpackSlot3;
            @BackpackSlot3.canceled -= instance.OnBackpackSlot3;
            @BackpackSlot4.started -= instance.OnBackpackSlot4;
            @BackpackSlot4.performed -= instance.OnBackpackSlot4;
            @BackpackSlot4.canceled -= instance.OnBackpackSlot4;
            @BackpackSlot5.started -= instance.OnBackpackSlot5;
            @BackpackSlot5.performed -= instance.OnBackpackSlot5;
            @BackpackSlot5.canceled -= instance.OnBackpackSlot5;
            @BackpackSlot6.started -= instance.OnBackpackSlot6;
            @BackpackSlot6.performed -= instance.OnBackpackSlot6;
            @BackpackSlot6.canceled -= instance.OnBackpackSlot6;
            @BackpackSlot7.started -= instance.OnBackpackSlot7;
            @BackpackSlot7.performed -= instance.OnBackpackSlot7;
            @BackpackSlot7.canceled -= instance.OnBackpackSlot7;
            @BackpackSlot8.started -= instance.OnBackpackSlot8;
            @BackpackSlot8.performed -= instance.OnBackpackSlot8;
            @BackpackSlot8.canceled -= instance.OnBackpackSlot8;
            @BackpackSlot9.started -= instance.OnBackpackSlot9;
            @BackpackSlot9.performed -= instance.OnBackpackSlot9;
            @BackpackSlot9.canceled -= instance.OnBackpackSlot9;
            @BackpackSlot10.started -= instance.OnBackpackSlot10;
            @BackpackSlot10.performed -= instance.OnBackpackSlot10;
            @BackpackSlot10.canceled -= instance.OnBackpackSlot10;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @Switch.started -= instance.OnSwitch;
            @Switch.performed -= instance.OnSwitch;
            @Switch.canceled -= instance.OnSwitch;
            @PrevNext.started -= instance.OnPrevNext;
            @PrevNext.performed -= instance.OnPrevNext;
            @PrevNext.canceled -= instance.OnPrevNext;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="InventoryActions.UnregisterCallbacks(IInventoryActions)" />.
        /// </summary>
        /// <seealso cref="InventoryActions.UnregisterCallbacks(IInventoryActions)" />
        public void RemoveCallbacks(IInventoryActions instance)
        {
            if (m_Wrapper.m_InventoryActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="InventoryActions.AddCallbacks(IInventoryActions)" />
        /// <seealso cref="InventoryActions.RemoveCallbacks(IInventoryActions)" />
        /// <seealso cref="InventoryActions.UnregisterCallbacks(IInventoryActions)" />
        public void SetCallbacks(IInventoryActions instance)
        {
            foreach (var item in m_Wrapper.m_InventoryActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InventoryActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="InventoryActions" /> instance referencing this action map.
    /// </summary>
    public InventoryActions @Inventory => new InventoryActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Inventory" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="InventoryActions.AddCallbacks(IInventoryActions)" />
    /// <seealso cref="InventoryActions.RemoveCallbacks(IInventoryActions)" />
    public interface IInventoryActions
    {
        /// <summary>
        /// Method invoked when associated input action "BackpackSlot1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBackpackSlot1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BackpackSlot2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBackpackSlot2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BackpackSlot3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBackpackSlot3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BackpackSlot4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBackpackSlot4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BackpackSlot5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBackpackSlot5(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BackpackSlot6" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBackpackSlot6(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BackpackSlot7" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBackpackSlot7(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BackpackSlot8" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBackpackSlot8(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BackpackSlot9" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBackpackSlot9(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BackpackSlot10" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBackpackSlot10(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Rotate" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotate(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Switch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSwitch(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PrevNext" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrevNext(InputAction.CallbackContext context);
    }
}
